org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=quickshulker_neoforged
mod_name=QuickShulker
mod_version=0.1.0
mod_group_id=com.ice2974.quickshulkerneoforged
mod_main_class=com.ice2974.quickshulkerneoforged.QuickShulkerNeoForged
archives_base_name=quickshulker-neoforged
mod_license=PolyForm Noncommercial License 1.0.0
mod_authors=Ice2974
mod_description=An unofficial Forge/NeoForge port of QuickShulker.

forge_minecraft_version=1.20.1
forge_version=1.20.1-47.4.20
forge_loader_version_range=[47,)
forge_minecraft_version_range=[1.20.1]
forge_java_version=17

neoforge_minecraft_version=1.21.1
neoforge_version=21.1.233
neoforge_loader_version_range=[21,)
neoforge_fml_version_range=[4,)
neoforge_minecraft_version_range=[1.21.1]
neoforge_java_version=21

moddevgradle_version=2.0.141
